# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7d34e297e51f6458a3c6cc71f0ba2da6"
name = "crocsvietnam: Tra cứu đơn hàng"
handle = "crocsvietnam-tra-cuu"
application_url = "https://crocsvietnam-tra-cuu.web.app/app/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders"

[auth]
redirect_urls = [
  "https://crocsvietnam-tra-cuu.web.app/api/auth/callback/"
]

[webhooks]
api_version = "2025-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://crocsvietnam-tra-cuu.web.app/api/webhooks/"

[app_proxy]
url = "https://crocsvietnam-tra-cuu.web.app/api/public/"
subpath = "tra-cuu-don-hang"
prefix = "apps"

[pos]
embedded = false
